# This is a basic workflow to help you get started with Actions

name: PublishToGithubPackages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [ published ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: '@educorvi'
          cache: 'yarn'
      - run: yarn install --immutable
      - run: echo always-auth=true >> .npmrc
      - run: echo registry=https://npm.pkg.github.com >> .npmrc
      - run: echo https://npm.pkg.github.com/:_authToken=$AUTH_TOKEN_SECRET
        env:
          AUTH_TOKEN_SECRET: ${{secrets.PUBLISH_GITHUB_PACKAGE_TOKEN}}
      - run: yarn npm publish
